import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./Navbar/page";
import Footer from "./Footer/page";
import SessionProvider from "@/public/components/SessionProvider";
import { ThemeProvider } from "./context/ThemeContext";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Shardev-Blog",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased ml-[10%] md:pl-[17%] md:ml-[80px] md:mr-[80px] mr-[10%] md:pr-[17%]`}
      >
        <SessionProvider>
          
        <Navbar/>
        {children}

        <Footer/>
        
        </SessionProvider>
      </body>
    </html>
  );
}
